var hsMath = {
			"math": [ { "question": "The x coordinate on the unit circle refers to  what trigonometry value", "answer": "cosine"},
			{"question" : "The y coordinate on the unit circle refers to  what trigonometry value", "answer": "sin"},
			{"question" : "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question":"", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""}, 
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": " ", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""}, 
			{"question": "", "answer": ""}, 
			{"question": "", "answer": ""},
			{"question" : "", "answer": ""},
			{"question": "", "answer": "" },
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question" : "" , "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer" : ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""},
			{"question": "", "answer": ""}]

		};

console.log(hsMath.math.length);